// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyADDCIwPz-Vfzvik7-b5u64CFxE0AHuSAw',
    appId: '1:798536850291:web:dca8820bb4375824c40306',
    messagingSenderId: '798536850291',
    projectId: 'madfinal-d541c',
    authDomain: 'madfinal-d541c.firebaseapp.com',
    storageBucket: 'madfinal-d541c.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBvGxEYagRyV9zD3XH0Rll7DYnZPiMO3GM',
    appId: '1:798536850291:android:3f5aa6a0bdbcdf14c40306',
    messagingSenderId: '798536850291',
    projectId: 'madfinal-d541c',
    storageBucket: 'madfinal-d541c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBlZ-THznLF0Y-EFBVF2n3GKtWTURh1Mf4',
    appId: '1:798536850291:ios:b3db3fc50255cd79c40306',
    messagingSenderId: '798536850291',
    projectId: 'madfinal-d541c',
    storageBucket: 'madfinal-d541c.appspot.com',
    iosClientId: '798536850291-n35bm2tn5m0kt3m55da3qdoru2n7clhh.apps.googleusercontent.com',
    iosBundleId: 'com.example.mad',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBlZ-THznLF0Y-EFBVF2n3GKtWTURh1Mf4',
    appId: '1:798536850291:ios:b3db3fc50255cd79c40306',
    messagingSenderId: '798536850291',
    projectId: 'madfinal-d541c',
    storageBucket: 'madfinal-d541c.appspot.com',
    iosClientId: '798536850291-n35bm2tn5m0kt3m55da3qdoru2n7clhh.apps.googleusercontent.com',
    iosBundleId: 'com.example.mad',
  );
}
